variables:
  NPM_MIRROR: https://registry.npmmirror.com

stages:
  - test
  - build
  - deploy

default:
  image: registry.gitlab.huajitech.net:5050/funnysyc/seamster

  cache:
    paths:
      - .cache/pip
      - $HOME/.npm
      - $HOME/.cache

  before_script:
    - python -V
    - node -v
    - poetry install

test:
  stage: test
  only:
    changes:
      - cyan/**/*
      - example/**/*
  script:
    - poetry run pyright
    - poetry run flake8

