image: nikolaik/python-nodejs:latest

variables:
  NPM_MIRROR: https://registry.npmmirror.com

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - .cache/pip
    - $HOME/.npm
    - $HOME/.cache

before_script:
  - python -V
  - node -v
  - poetry install

test:
  stage: test
  only:
    changes:
      - cyan/**/*
      - example/**/*
  script:
    - poetry run pyright
    - poetry run flake8

build:
  stage: build
  only:
    refs:
      - tags
    changes:
      - cyan/**/*
  script:
    - poetry build
  artifacts:
    paths:
      - dist

publish:
  stage: deploy
  only:
    refs:
      - tags
  needs:
    - job: build
      artifacts: true
  script:
    - poetry publish

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    refs:
      - tags
  script:
    - echo "Running the release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Cyan v$CI_COMMIT_TAG'
    description: '这是 GitLab CI 自动部署，更新日志将会手动更新。'

pages:
  stage: deploy
  only:
    refs:
      - tags
  script:
    - cd docs
    - poetry run sphinx-apidoc -o . ../cyan
    - poetry run sphinx-build -b html . ./build
    - mv ./build ../public
  artifacts:
    paths:
      - public
