image: nikolaik/python-nodejs:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYPI_MIRROR: https://pypi.tuna.tsinghua.edu.cn/simple
  NPM_MIRROR: https://registry.npmmirror.com

cache:
  paths:
    - .cache/pip
    - $HOME/.npm
    - $HOME/.cache

before_script:
  # For debugging
  - python -V
  - node -v

test:
  only:
    changes:
      - cyan/**/*
      - example/**/*
  script:
    - poetry install
    - poetry run pyright
    - poetry run flake8
