image: nikolaik/python-nodejs:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYPI_MIRROR: https://pypi.tuna.tsinghua.edu.cn/simple
  NPM_MIRROR: https://registry.npmmirror.com

cache:
  paths:
    - .cache/pip
    - venv/
    - $HOME/.npm

before_script:
  # For debugging
  - python -V
  - node -v

  - pip install poetry -q -i $PYPI_MIRROR
  - poetry shell

test:
  script:
    - poetry install
    - npm install -g pyright --registry $NPM_MIRROR

    - pyright
    - flake8
